### ISSUE TITLE
Proper calibration with App - incorrect mapping

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#109]
I have installed OttoBlockly 1.4.3
I opened "Proper calibration with App | Otto DIY Starter example"
I viewed the arduino code and checked that the PINS are mapped correctly.
I downloaded the calibration code from https://www.ottodiy.com/academy.
The file is Otto_Servo_Calibration_UPDATE2.zip.

When I run the application (64-bit version), the sliders control the wrong servos:

Right leg - correct
Left leg - nothing moves
Right foot - correct
Left foot - controls the left leg

I noticed that there was a bloc in the ZIP file - "Otto_Servo_Calibration.bloc".
This file is significantly different from the example.
When I load this file and run the calibration, all sliders control only the right leg, and the servo jitters like crazy.

**Comment by cparrapa** [comment]
Thank @brendonhatcher 
We just fixed it here https://github.com/OttoDIY/blockly/blob/master/www/examples/Ottocalibrationapp.xml you can update this file in your installation and it should work or wait until new Otto BLockly 1.4.4 comes out
