### ISSUE TITLE
Sound example issues

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#110]
Using Blockly 1.4.3
I added a noise sensor using the pins in the Google Presentation "Getting started with Otto DIY robots".

If I use the "Serial noise readings | +sensor" example, it works correctly.
If I use "Sound interaction | +sensor" then the Otto doesn't move when I make a sound.

The reason appears to be that "Sound interaction" uses digitalRead to gather data from the analogue sound sensor and treat it as high or low.
According to Arduino, A6 on a Nano cannot be used for digital readings: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalread/

The Sound interaction example needs to change to: https://imgur.com/a/Kxk59wd

**Comment by cparrapa** [comment]
Thanks for noticing fixed already for next release
