### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by AIoTvn** [OttoDIY/blockly#114]
OttoBlockly 1.4.3

I have this error when press check the code before upload code to robot board.  What can i do for solve this problem ?? :(( 
![image](https://user-images.githubusercontent.com/57827772/132883303-72d3fa47-ef65-4cef-9a7c-158fe51c4212.png)
![image](https://user-images.githubusercontent.com/57827772/132883425-9b8e93de-a18f-4109-9c86-23ae508b457e.png)

**Comment by cparrapa** [comment]
Hi @AIoTvn 
Can you upload the code you are trying to compile here?
