### ISSUE TITLE
Variable block language issue in English

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#120]
I think that there is a language translation issue in variables.
When I create a variable, the blocks don't make perfect sense in English, and I wonder if they were translated literally from another language?

e.g. "put the variable xxxx at" should probably be "set the variable xxx to"

![variable block wording](https://user-images.githubusercontent.com/61579046/134167344-edb5b479-8c44-4383-95b7-e5559227eb4f.PNG)

**Comment by cparrapa** [comment]
Hi @brendonhatcher 
Indeed these blocks have been a nightmare also for us.
I am thinking then to use more simple English How about like this?
![image](https://user-images.githubusercontent.com/8412468/134425075-f980e3cd-1f0d-4f28-aae3-e28f8ccc45e2.png)

**Comment by brendonhatcher** [comment]
I'll have a look at what each does and then suggest some text changes.

**Comment by cparrapa** [comment]
Thanks let me know and we add as you request @brendonhatcher

**Comment by cparrapa** [comment]
how about  like this ? @brendonhatcher 
![image](https://user-images.githubusercontent.com/8412468/136475922-a6b84a80-5674-4252-81ed-061f0fd02e7e.png)
