### ISSUE TITLE
Handwave moves both arms!

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#123]
I am using only the "Arms (handwave left)" block inside the loop.  The arm moves as expected.  However, the other arm also moves at random times! Without any instruction to that arm!

**Comment by cparrapa** [comment]
hahaha that is funny @brendonhatcher  i will check that and fix maybe we will have to roll back to independent Humanoid blocks

**Comment by cparrapa** [comment]
@brendonhatcher  This has been solved in in the latest release https://github.com/OttoDIY/blockly/releases/tag/v1.4.9
