### ISSUE TITLE
Example: 👨‍💻Level 2 | 👄 8x8 LED Matrix Test | +mouth - repaint is wrong

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#124]
The test doesn't clear the "screen" between the line test and the symbol.
It needs a "clear" block in the setup and at the end of the loop

**Comment by cparrapa** [comment]
fixed here https://github.com/OttoDIY/blockly/commit/7c48c63fbb53a7074c2005c5d482aa721a6d4378
Thanks @brendonhatcher
