### ISSUE TITLE
Double Include Otto.h

### ISSUE THREAD

**Issue by gurues** [OttoDIY/blockly#130]
Hellow, I have an error when I setup matrix MAX7219, servos and buzzer there is a double #include Otto.h and Object Ottto what causes an erro
![Captura2](https://user-images.githubusercontent.com/35085918/136862132-2541db9e-4cd5-4180-b00a-4d3a43587c82.JPG)
r

**Comment by cparrapa** [comment]
Thanks @gurues 
Solved in this commit https://github.com/OttoDIY/blockly/commit/7c48c63fbb53a7074c2005c5d482aa721a6d4378 it will be ok in version 1.4.4 coming soon
