### ISSUE TITLE
Add Arabic support

### ISSUE THREAD

**Issue by arieleren** [OttoDIY/blockly#142]

**Comment by arieleren** [comment]
[Blockly_ar.zip](https://github.com/OttoDIY/blockly/files/7799001/Blockly_ar.zip)

**Comment by cparrapa** [comment]
Hi @arieleren 
Can you do a pull request please?

**Comment by arieleren** [comment]
Here is the merge request URL:
https://github.com/OttoDIY/blockly/pull/143

**Comment by cparrapa** [comment]
Great thanks it will be in the next release

**Comment by cparrapa** [comment]
Hi @arieleren this only contains the blockly part translation is that all you need?
