### ISSUE TITLE
Built application displays nothing but a white screen (for windows)

### ISSUE THREAD

**Issue by kiranchhablani** [OttoDIY/blockly#156]
I tried to build the application with some minor changes. When I execute the exe file it only shows a white screen. I'm talking about v1.4.2. I'm using this version in the new version it is not detecting the USB port.

I also tried to build without changing anything. Still facing the same issue. Can someone help me with this

**Comment by jigneshk5** [comment]
Any update on this issue @kiranchhablani

**Comment by cparrapa** [comment]
Hi @kiranchhablani 
Follow step by the readme and you wont have this problem
