### ISSUE TITLE
blockly log?

### ISSUE THREAD

**Issue by casusbelli** [OttoDIY/blockly#158]
Does blockly write a log of it's operations that can be used for debugging when things have an issue?
(Upload to Otto has issues in my setup which i'd like to take a closer look into).
Thanks

**Comment by cparrapa** [comment]
Hi @casusbelli 
When you click compile if not successful, it gives you a set of errors that are the same as in Arduino IDE, maybe it needs to presented in a more clean way, but I am not sure how to do that

**Comment by casusbelli** [comment]
Hi @cparrapa !
Thanks for the feedback.
In my case the "Uploading..." is shown in black  for a split second and then turns red, no more output after that.
The whole UI is blocked by that dialogue (red "Uploading...") and I've to kill it in order to re-run.
That's why I was looking for a log file on disk.

I'll see if the Arduino IDE might help.

**Comment by cparrapa** [comment]
use F8 to open the console @casusbelli
