### ISSUE TITLE
Music figure icon misisng on buzzer block

### ISSUE THREAD

**Issue by IvanR3D** [OttoDIY/blockly#167]
The music figures for "whole" and "half" are missing in the 3rd block of the Buzzer section. 
![Captura de Pantalla 2022-06-01 a la(s) 6 32 13 p  m](https://user-images.githubusercontent.com/34162904/171512583-9b352da6-0af7-423d-947f-7057a0668a49.png)

**Comment by cparrapa** [comment]
Thanks @IvanR3D 
Fixed in https://github.com/OttoDIY/blockly/commit/03860be0e943fb8cb3b3399f83ff19866b9a86ab
