### ISSUE TITLE
Redundant Arduino code when using buzzer blocks

### ISSUE THREAD

**Issue by IvanR3D** [OttoDIY/blockly#168]
Using the buzzer blocks as shown in the picture, generate this Arduino code:
```
void setup() {
  pinMode( 13 , OUTPUT);
  pinMode(13, OUTPUT);
    tone(  13,261,125);
   delay(125);
  tone(13,440,1000);
  delay(1000);
}
void loop() {
}
```
Declaring the pinMode 2 times. 
![Captura de Pantalla 2022-06-03 a la(s) 5 50 55 p  m](https://user-images.githubusercontent.com/34162904/171958768-499086f9-9b76-4d3c-9d39-ff6d5d8478ce.png)

Maybe creating a block to declare the pinMode and taking this line out of the blocks could be useful for this.

**Comment by cparrapa** [comment]
Thanks @IvanR3D 
Fixed in https://github.com/OttoDIY/blockly/commit/03860be0e943fb8cb3b3399f83ff19866b9a86ab
