### ISSUE TITLE
Language switch requires page refresh/app restart

### ISSUE THREAD

**Issue by BodoMinea** [OttoDIY/blockly#17]
@BodoMinea do you also experience that switching between languages, that sometimes does not work immediately? like is necessary to refresh (F5) or even restart the app and therefore deletes all current blocks? maybe we need something more instant or automatically for general users, just a thought. 

Similar situation with the setting (Language & Blocks menu) the level sometimes get mixed or showing the categories of other levels instead?

_Originally posted by @cparrapa in https://github.com/OttoDIY/blockly/issues/7#issuecomment-578526603_

**Comment by cparrapa** [comment]
fixed in 32f19d8
