### ISSUE TITLE
could not compile anything in blackly

### ISSUE THREAD

**Issue by rameshdanaraddi** [OttoDIY/blockly#175]
getting this msg
Error: Command failed: arduino-cli.exe compile --fqbn arduino:avr:nano sketch/sketch.ino panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xd9d905] goroutine 1 [running]: github.com/arduino/go-properties-orderedmap.(*Map).Get(...) /github/home/go/pkg/mod/github.com/arduino/go-properties-orderedmap@v1.3.0/properties.go:223 github.com/arduino/arduino-cli/legacy/builder.(*WipeoutBuildPathIfBuildOptionsChanged).Run(0x19e8750, 0xc000100000, 0x19e8750, 0x0) /__w/arduino-cli/arduino-cli/legacy/builder/wipeout_build_path_if_build_options_changed.go:48 +0x1d5 github.com/arduino/arduino-cli/legacy/builder.(*ContainerBuildOptions).Run(0x19e8750, 0xc000100000, 0x19e8750, 0x0) /__w/arduino-cli/arduino-cli/legacy/builder/container_build_options.go:35 +0x128 github.com/arduino/arduino-cli/legacy/builder.runCommands(0xc000100000, 0xc0004d7248, 0x20, 0x20, 0x0, 0x0) /__w/arduino-cli/arduino-cli/legacy/builder/builder.go:187 +0x1a6 github.com/arduino/arduino-cli/legacy/builder.(*Builder).Run(0xc0004d74c0, 0xc000100000, 0x1255100, 0xc001d04270) /__w/arduino-cli/arduino-cli/legacy/builder/builder.go:97 +0xb89 github.com/arduino/arduino-cli/legacy/builder.RunBuilder(...) /__w/arduino-cli/arduino-cli/legacy/builder/builder.go:205 github.com/arduino/arduino-cli/commands/compile.Compile(0x124c100, 0xc000030118, 0xc0004d7c70, 0x12320e0, 0xc000006018, 0x12320e0, 0xc000006020, 0x0, 0x0, 0x0, ...) /__w/arduino-cli/arduino-cli/commands/compile/compile.go:215 +0x17ac github.com/arduino/arduino-cli/cli/compile.run(0xc0002aa840, 0xc0002aeb40, 0x1, 0x3) /__w/arduino-cli/arduino-cli/cli/compile/compile.go:155 +0x412 github.com/spf13/cobra.(*Command).execute(0xc0002aa840, 0xc0002aeb10, 0x3, 0x3, 0xc0002aa840, 0xc0002aeb10) /github/home/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710201246-675ae5f5a98c/command.go:846 +0x2b1 github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a5080, 0x33, 0xc000298000, 0xc00002d340) /github/home/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710201246-675ae5f5a98c/command.go:950 +0x350 github.com/spf13/cobra.(*Command).Execute(...) /github/home/go/pkg/mod/github.com/spf13/cobra@v1.0.1-0.20200710201246-675ae5f5a98c/command.go:887 main.main() /__w/arduino-cli/arduino-cli/main.go:31 +0x8c

**Comment by cparrapa** [comment]
Hi @rameshdanaraddi 
Can you post the code here that you are trying to compile both blocks and text code please?
