### ISSUE TITLE
Otto Blockly can't compile anything - LINUX

### ISSUE THREAD

**Issue by NPFabLabEcoCentre** [OttoDIY/blockly#176]
Hi all.
I need help on this.

My computer is an old macBook (white unibody one) with linux mint 20.2
I just installed Arduino IDE using the GUI interface and it work like a charm. I'm able to connect to the Otto, send it a program and upload it each time.

Then, I installed Otto Blockly using the Linux install package I found online on the webSite.
Everything works fine. Except I can't verify my code (compile it) neither upload it cause it doesn't compile.

The error i get is the following : 

> Error: Command failed: ./arduino-cli compile --fqbn arduino:avr:nano sketch/sketch.ino /bin/sh: 1: ./arduino-cli: not found

Then I tried to install the Arduino-cli thing.... by installing Arduino-builder and Arduino-mk... didn't work.
Tried adding my Arduino folder to my $PATH.... same.

Does anyone have an idea on how to fix this please ?  ;p
Thank's !

**Comment by ale3andro** [comment]
Hello, the same problem here (Ubuntu 22.04.3 LTS)
Solution for me is hard coding the location of arduino-cli tool
In the file 
**_/opt/OttoBlockly/resources/app_** 
change the 4 occurencies of 
**_./arduino-cli_**
to
**_/opt/OttoBlockly/arduino-cli_**
Restart OttoBlockly app
It works for me now, I am able to compile and upload code to Otto
Hope it helps.
Alex
