### ISSUE TITLE
esp8266 ultrasound not working in v 1.5

### ISSUE THREAD

**Issue by jojumohan** [OttoDIY/blockly#190]
I have tried to use ultrasound in ESP 8266 but it is showing a constant value it is working in Arduino programming can you please fix it

**Comment by cparrapa** [comment]
Hi @jojumohan are you using a HC-SR04 ultrasonic module with TRIG and ECHO pins?
The same code is working in arduino?

**Comment by jojumohan** [comment]
yes I figured it out I edited some blocks in XML now it is working thanks for response

**Comment by jojumohan** [comment]
thanks

**Comment by cparrapa** [comment]
Hi @jojumohan  can you tell us please what changes you made so we fix it?

**Comment by jojumohan** [comment]
hi
i changed ultrasonic_distance2 to ultrasonic_distance in toolbox folder
toolbox_arduino_all-esp8266.xml so I got old ultra-sound block
now i can use HC-SR04
