### ISSUE TITLE
ottoky eyes block not present

### ISSUE THREAD

**Issue by jojumohan** [OttoDIY/blockly#191]
esp8266 has 1.3-inch OLED  support and a lot of expressions for eyes it will be good to see similar block in Ottoky

**Comment by cparrapa** [comment]
Hi @jojumohan 
Good idea we will add that in the next release, so you prefer to code Ottoky with Otto Blockly than with tokylabs blockly?

**Comment by jojumohan** [comment]
Yes it is having Arduino structure and in the future, I want to make students code with the Arduino platform
