### ISSUE TITLE
Where is the installer package for Mac OS?

### ISSUE THREAD

**Issue by jagadish85** [OttoDIY/blockly#207]

**Comment by sfranzyshen** [comment]
unfortunately there is no MacOS installer ... you will have to build from the source ... If you do succeed in building the binaries you are welcome to provide an archive and we will share in the releases ...

**Comment by gasperzupancic** [comment]
it would only be fair that you review your documentation and links in the how to guides.

**Comment by cparrapa** [comment]
We did not manage to create the installer like it was for windows releases. Until someone with Mac experience comes, is not possible to use Mac OS.
