### ISSUE TITLE
Servo not declared in this scope 

### ISSUE THREAD

**Issue by Vpelitegamer** [OttoDIY/blockly#209]
Whenever i want to check my not virtually through simulations in online the block code which i did and converted it in text code in otto blockly and entered in the simulation to check if this works correctly before entering in the physical robot.. And its showing servo_3 not declared in this scope.. is this a bug or ami missing anything in the libraray.. Im currently 1.4,7 version of otto blockly and should i upgrade to 1.5.0 to get that fixed

**Comment by cparrapa** [comment]
yes you must use the latest version
