### ISSUE TITLE
Mouth - display variable

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#22]
I created an int variable and declared it. I added the Mouth block and tried to connect the variable block to it. Instead of showing the number, the led matrix displays the name of the variable.

The variable is storing an integer value. If I use the Pixel X/Y block, I can use the value of the variable to input the X and Y coordinates.

The "S" in the attached image is Otto scrolling the word CLAPS

![Otto clap](https://user-images.githubusercontent.com/61579046/75550298-89c88400-5a29-11ea-80e4-0da175431e72.PNG)

**Comment by cparrapa** [comment]
Oh i got your idea is pretty cool you want Otto to turn led by led every time you clap.

**Comment by cparrapa** [comment]
ok solved here https://github.com/OttoDIY/blockly/commit/eb144a958a705dfbbeeddb8ab79ae72d074bc9a9
