### ISSUE TITLE
Simplfy Check and Upload

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#23]
The current process of pressing Check, then closing the popup, then pressing Upload, then closing the popup is very annoying when you are making lots of edits.  

It would be great if pressing it would do both the check code and upload and then close the popup. 
The check code button should remain for users to check without uploading.

This change would match the Arduino IDE user interface.

**Comment by cparrapa** [comment]
You are right still trying to figure out how to solve this, it seems blockly needs to separately do both task.

**Comment by cparrapa** [comment]
it was not easy to fix! but somehow i think i managed here https://github.com/OttoDIY/blockly/commit/59b7edae2e709e1103305912daaf00739ff8b3e2
