### ISSUE TITLE
Bluetooth connection

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#24]
Is it possible to connect OttoBlockly to my Otto Humanoid via bluetooth instead of a USB cable?

**Comment by brendonhatcher** [comment]
@OttoDIY responded on facebook: good idea for a new feature, we tried to make it at least using the software serial communication it should be possible (like a replacement of the APP control), connect is easy, but programming is more complex that it sounds.

**Comment by cparrapa** [comment]
@brendonhatcher  it is very complicated actually, i myself tried even just with Arduino IDE and still not success https://www.instructables.com/id/Arduino-Bluetooth-Programming/

**Comment by cparrapa** [comment]
Hi for this we have create Otto Scratch AI https://www.ottodiy.com/academia
