### ISSUE TITLE
HELP need to add the new Arduino Nano Every board

### ISSUE THREAD

**Issue by cparrapa** [OttoDIY/blockly#36]
is an actual continuation of the issue #2 but specifically for the new Arduino Nano Every https://store.arduino.cc/nano-every-pack

i get to the point that i add the definitions in the boards.txt but i still get error when compiling
![image](https://user-images.githubusercontent.com/8412468/83635856-383e1100-a5a5-11ea-9633-c3fb9d3a5863.png)

Any clues @BodoMinea ?

**Comment by BodoMinea** [comment]
I think you should try installing the Every boards in a separate Arduino install and then copy what´s missing to the Otto Blockly compiler resources. I am pretty sure I can do it but I currently don´t have the time to contribute.

**Comment by cparrapa** [comment]
Hi @BodoMinea 
Yes good idea i was trying that using the Arduino IDE files that have the Every functional and copying them to the compiler, but it just got worse damaging the opiboot and other nano boards.
![image](https://user-images.githubusercontent.com/8412468/83656312-aabbea80-a5bf-11ea-967a-074207eb5dde.png)
![image](https://user-images.githubusercontent.com/8412468/83656079-66c8e580-a5bf-11ea-888a-5601faadb802.png)
Later on I even managed to compile one time but then i try to upload and 
![image](https://user-images.githubusercontent.com/8412468/83656361-b9a29d00-a5bf-11ea-9f6c-b4dce54bb587.png)

I think we are close but i am not sure what toolset i need to modify or add there.

Thanks for your time like this giving me advice and tips it will greatly help us.

**Comment by cparrapa** [comment]
Fixed in #76  thanks to @logix5
