### ISSUE TITLE
Driver install failure of CH341SER.INF

### ISSUE THREAD

**Issue by mxochicale** [OttoDIY/blockly#37]
Hi all,

As suggested in the [readme](https://github.com/OttoDIY/blockly#installer), I downloaded the [latest version](https://github.com/OttoDIY/blockly/releases) of otto blocky and installed OttoBlockly-Setup-1.2.0.exe and also tried OttoBlockly-1.2.0.exe in a windowsX64 machine. However none of them recognise the USB device. So I am trying to execute SETUP.exe downloaded from the suggested [path: pilotes/_CH341](https://github.com/OttoDIY/blockly/tree/master/pilotes/_CH341) which results in the following installation failure: 

![Capture](https://user-images.githubusercontent.com/11370681/85933904-0eda8180-b8d4-11ea-9b9f-9016843bb600.PNG)

I might be missing something. I am wondering if you any recommendations?

**Comment by cparrapa** [comment]
Hi @mxochicale 
Good to see you here! driver hmmmm did you try to install from here  https://sparks.gogo.co.nz/ch340.html ? some computers are picky with the CH340 devices like the nano. 

What Windows are you running? even in my Windows 10 i did not need to install and the USB was recognized automatically.

**Comment by mxochicale** [comment]
Many thanks Camilo, finally here to mention that I was not connecting the USB cable to OTTO which might be the reason to have the driver installation error. So after connecting it, the driver is successfully installed under window 10 Home version 1803 and I can happily play with some of the nice examples you show [here](https://www.youtube.com/watch?v=chcWxh4Co_c) :) 

![sorted](https://user-images.githubusercontent.com/11370681/86496378-1cc95000-bd75-11ea-894a-148f0e1dde39.PNG)

I close the issue now but I guess feel free to re-open it if you or anyone has similar problems.
