### ISSUE TITLE
Add a vision camera for doing IA applications

### ISSUE THREAD

**Issue by logix5** [OttoDIY/blockly#49]
Hi ,  My robotic kit use an arduino Leonardo board compatible and i have been creating my own enviroment in Blockly.  You can see [here](https://logix5.com/Blockyduino-para-MRTDuino/). I have added a lot of sensors, actuator, cameras,... 

the project in github [here](https://github.com/logix5/Blocklyduino-para-MRTDuino)

Now I am going to start with otto, and probably migrate your otto blocks to my tool, but in my opinion would be interesting add a camera as Mu Vison to otto by I2C port. Maybe in the next months, i can do it and share here. The camera is easy to integrate using the library and some vision applicaton are available and give to otto an important plus.
Another camera to work  is this: https://www.dfrobot.com/product-1922.html maybe more interesting and with panel to see.

I let you know, if at the end add this feature. I am not expert in JavaScript and i would like to create in my tool the option to change the arduino board because the most of blocks are compatible in different pins. Now for otto i will use the nano board.

Thanks

**Comment by cparrapa** [comment]
@logix5 
This is great so we can just use the same .js files and bring them here? i was thinking to incorporate the MU but this will be a time saver thanks!

**Comment by logix5** [comment]
I have added in my repository the blocks to use Mu Vision camera in blockly for Arduino. Beside I have added some blocks of  your blockly otto extension :-) too

https://github.com/logix5/Blocklyduino-para-MRTDuino

mu_vision_sensor2.js file  in blocks and generators. you need to copy the language texts and add in your program. you can insert in your application

Thanks!

**Comment by cparrapa** [comment]
thanks to you @logix5  i will give a try this weekend

**Comment by cparrapa** [comment]
Morpx added here https://github.com/OttoDIY/blockly/pull/66
