### ISSUE TITLE
Failed to download repository

### ISSUE THREAD

**Issue by ksonone** [OttoDIY/blockly#50]
failed to download repository
![error](https://user-images.githubusercontent.com/26852284/92425473-068ca580-f1a5-11ea-8881-ffd7e7aaf3f3.png)

**Comment by sfranzyshen** [comment]
I can confirm this is happening ... but I was successful after choosing try again multiple times it finally finished ... I was also able to download using the website interface as a zip file ... sorry but this is out of the hands of the developers here at this project ... it's a github issue ... please close this issue after you have had a chance to retry (again and again) good luck 😄

**Comment by ksonone** [comment]
Great! It works. Thanks a lot.
