### ISSUE TITLE
Adding Arduino code to Otto blockly so the two work as one.

### ISSUE THREAD

**Issue by cadcygnus** [OttoDIY/blockly#53]
I think it would be very helpful to figure out a block or make a block that you can copy and paste the Arduino code into that will work alongside the other blocks in blockly.  Imagine how powerful this will make Otto blockly not only can you run code but you can add blocks to the code that was used for an example in Ardunio.  Here would be a small example.  You want your project to use the blockly servos, the blockly loops, timing, led mouth, and leg calibration.  Now you also want to add some OLEDs and new pixels from a code somebody else wrote on Github or youtube.  If all you had to do was paste that code into the program using a block and it would automatically write into the code that is there from the blocks you used

**Comment by cparrapa** [comment]
Hi @cadcygnus
You can already do that check the structure in the toolbar it has this block
![image](https://user-images.githubusercontent.com/8412468/95990338-a9cb7d00-0e2b-11eb-94fc-80c76ab77151.png)
and you can always just use the Arduino mode! press the puzzle button in the top left corner
