### ISSUE TITLE
Block category icons disappear after switching language from default

### ISSUE THREAD

**Issue by BodoMinea** [OttoDIY/blockly#7]
English:
![en](https://user-images.githubusercontent.com/7822580/73016495-a0762c80-3e26-11ea-908e-5a2364cc8639.png)
French:
![fr](https://user-images.githubusercontent.com/7822580/73016505-a4a24a00-3e26-11ea-90e9-7c37f83d8fb9.png)
The icons should remain the same. Any idea why this is happening?

**Comment by cparrapa** [comment]
It is just not updated, don´t worry but yes we have´re check all the lang files, some community members are maybe gonna help to add new languages, so then we can make them consistent. Or any suggestion how to deploy and easy collaborative way to translate?

**Comment by BodoMinea** [comment]
Fixed, PR #10

**Comment by cparrapa** [comment]
Thanks, 
@BodoMinea do you also experience that switching between languages, that sometimes does not work immediately? like is necessary to refresh (F5) or even restart the app and therefore deletes all current blocks? maybe we need something more instant or automatically for general users, just a thought. 

Similar situation with the setting (Language & Blocks menu) the level sometimes get mixed or showing the categories of other levels instead?

**Comment by BodoMinea** [comment]
This is a separate issue.
