### ISSUE TITLE
Disconnected blocks

### ISSUE THREAD

**Issue by brendonhatcher** [OttoDIY/blockly#88]
Hi. On the idea that all blocks run, even if not connected to a trigger... Our intent in using Blockly is to teach computational thinking.  As such, the output behaviour of the system should be consistent with standard coding practices, otherwise we allow / encourage / reinforce poor thinking and practice.  I think it is essential that disconnected blocks do NOT run.  If we want to make it easier for our users, it would be better if the “check the code” button (and its runtime during “upload to robot”) post a message saying “You have one or more unconnected blocks.  These cannot run.  Either connect the block, or right click and disable it”.

**Comment by cparrapa** [comment]
Thanks @brendonhatcher 
Now we have added the setup/loop block as default when opening blockly and any bloc of Otto requires to use the config in the setup bloc to works
