### ISSUE TITLE
Logic and Math menu bug in the Portuguese version

### ISSUE THREAD

**Issue by lsprandel** [OttoDIY/blockly#96]
Hello,
when we are using on portuguese translation the menu of Logic and Math doesnt show correctly. This failure compromises the use in this language. 
Thanks a lot. 

![Math_bug_portuguese](https://user-images.githubusercontent.com/45643092/107850310-3721dc80-6de0-11eb-98e4-728328d16ef7.png)
![Logic_bug_portuguese](https://user-images.githubusercontent.com/45643092/107850312-37ba7300-6de0-11eb-8393-e273bbb7ce0c.png)

**Comment by cparrapa** [comment]
Thanks for letting us know @lsprandel

fixed here https://github.com/OttoDIY/blockly/commit/4fab97787b20566399432b4475bf130c986537ac

Download this file https://github.com/OttoDIY/blockly/blob/master/www/lang/Blockly_pt.js and replace in your installed blockly 

Let me know if works for you

**Comment by elton-bt** [comment]
The solution works!
